### ISSUE TITLE
metal: error:       PLL Lock timeout error in XRFdc_WaitForRestartClr

### ISSUE THREAD

**Issue by Jingyi-li** [Xilinx/PYNQ_RFSOC_Workshop#5]
Hi, as I was runing the 02_pynq_and_data_converter.ipynb. I got some error. Can you please help me? Thank you very much. 

Details are :

metal: error:     
 PLL Lock timeout error in XRFdc_WaitForRestartClr

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-9-5e2e545efa1a> in <module>
----> 1 ol = QpskOverlay(init_rf_clks=False)

/usr/local/lib/python3.6/dist-packages/rfsoc_qpsk/qpsk_overlay.py in __init__(self, bitfile_name, init_rf_clks, dark_theme, presentation_mode, **kwargs)
    115 
    116         # Set sane DAC defaults
--> 117         self.dac_tile.DynamicPLLConfig(1, 409.6, 1228.8)
    118         self.dac_block.NyquistZone = 2
    119         self.dac_block.MixerSettings = {

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in DynamicPLLConfig(self, source, ref_clk_freq, samp_rate)
    222 
    223     def DynamicPLLConfig(self, source, ref_clk_freq, samp_rate):
--> 224         self._call_function("DynamicPLLConfig", source, ref_clk_freq, samp_rate)
    225 
    226 

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _call_function(self, name, *args)
    201 
    202     def _call_function(self, name, *args):
--> 203         return self._parent._call_function(name, self._type, self._index, *args)
    204 
    205     def _call_function_implicit(self, name, *args):

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _call_function(self, name, *args)
    260 
    261     def _call_function(self, name, *args):
--> 262         _safe_wrapper(f"XRFdc_{name}", self._instance, *args)
    263 
    264 

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _safe_wrapper(name, *args, **kwargs)
     59             raise RuntimeError(f"Function {name} not in library")
     60         if getattr(_lib, name)(*args, **kwargs):
---> 61             raise RuntimeError(f"Function {name} call failed")
     62 
     63 

RuntimeError: Function XRFdc_DynamicPLLConfig call failed

**Comment by dnorthcote** [comment]
Hi Jingyi-li,

I have a few questions that will help me understand the error better. 

* Are you using the ZCU111 development board?
* What version of PYNQ are you using?
* Are you using a fresh install of PYNQ?

Finally, try and change init_rf_clks to True when calling the QpskOverlay class. Uninitialized clocks seem to be causing the problem,

Thanks,
David.

**Comment by schelleg** [comment]
closing since no further replies ... please reopen if still an issue.

**Comment by tkgunaratne** [comment]
> Hi Jingyi-li,
> 
> I have a few questions that will help me understand the error better.
> 
> * Are you using the ZCU111 development board?
> * What version of PYNQ are you using?
> * Are you using a fresh install of PYNQ?
> 
> Finally, try and change init_rf_clks to True when calling the QpskOverlay class. Uninitialized clocks seem to be causing the problem,
> 
> Thanks, David.

I too have the same similar even after modifying "ol = QpskOverlay(init_rf_clks=True)".
`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-46ecb4afa610> in <module>()
----> 1 ol = QpskOverlay(init_rf_clks=True)

/usr/local/lib/python3.6/dist-packages/rfsoc_qpsk/qpsk_overlay.py in __init__(self, bitfile_name, init_rf_clks, dark_theme, presentation_mode, **kwargs)
    127 
    128         # Set sane ADC defaults
--> 129         self.adc_tile.DynamicPLLConfig(1, 409.6, 1228.8)
    130         self.adc_block.NyquistZone = 2
    131         self.adc_block.MixerSettings = {

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in DynamicPLLConfig(self, source, ref_clk_freq, samp_rate)
    222 
    223     def DynamicPLLConfig(self, source, ref_clk_freq, samp_rate):
--> 224         self._call_function("DynamicPLLConfig", source, ref_clk_freq, samp_rate)
    225 
    226 

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _call_function(self, name, *args)
    201 
    202     def _call_function(self, name, *args):
--> 203         return self._parent._call_function(name, self._type, self._index, *args)
    204 
    205     def _call_function_implicit(self, name, *args):

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _call_function(self, name, *args)
    260 
    261     def _call_function(self, name, *args):
--> 262         _safe_wrapper(f"XRFdc_{name}", self._instance, *args)
    263 
    264 

/usr/local/lib/python3.6/dist-packages/xrfdc/__init__.py in _safe_wrapper(name, *args, **kwargs)
     59             raise RuntimeError(f"Function {name} not in library")
     60         if getattr(_lib, name)(*args, **kwargs):
---> 61             raise RuntimeError(f"Function {name} call failed")
     62 
     63 

RuntimeError: Function XRFdc_DynamicPLLConfig call failed`

* Are you using the ZCU111 development board? Yep 
* What version of PYNQ are you using? 2.7
 * Are you using a fresh install of PYNQ? No
