### ISSUE TITLE
the Jupyter 9090 port login requires password

### ISSUE THREAD

**Issue by zhizhenzhong** [Xilinx/PYNQ_RFSOC_Workshop#7]
I load the PYNQ 2.7 image downloaded from the official website on my ZCU111 board, and I connect the board to a network switch. I can use another computer to access the PYNQ Jupyter notebook environment, but the 9090 port needs a password. I do not find an available password to login. Any clues？

**Comment by cathalmccabe** [comment]
Password is:
xilinx

**Comment by zhizhenzhong** [comment]
Thanks, Cathal. It works.
